import {
  LayoutDashboard,
  BookOpen,
  CalendarCheck,
  ClipboardList,
  Bell,
  FolderOpen,
  Users,
  UserPlus,
  Star,
  Shield,
  Zap,
  BarChart3,
  MessageCircle,
  Trophy,
} from 'lucide-react'

/* ──────── Landing Page Tour ──────── */
export const landingTourSteps = [
  {
    target: '#hero',
    title: 'Welcome to CS Department LMS',
    subtitle: 'Govt. Graduate College Burewala',
    content: 'This is the homepage of our Learning Management System. Let us show you around!',
    icon: Star,
    placement: 'bottom',
  },
  {
    target: 'a[href="/register"]',
    title: 'Get Started',
    subtitle: 'Create your account',
    content: 'Click here to register as a student or teacher. You will need your college email and phone number for OTP verification.',
    icon: Zap,
    placement: 'bottom',
  },
  {
    target: 'a[href="/login"]',
    title: 'Sign In',
    subtitle: 'Already have an account?',
    content: 'If you already have an account, click Sign In to access your personalized dashboard.',
    icon: Shield,
    placement: 'bottom',
  },
  {
    target: '#problem',
    title: 'Why CS Department LMS?',
    subtitle: 'The problem we solve',
    content: 'Manual attendance, lost assignments, scattered communication — we digitize all of it for the CS Department.',
    icon: BarChart3,
    placement: 'bottom',
  },
  {
    target: '#solution',
    title: 'Our Features',
    subtitle: 'Everything in one place',
    content: 'Digital attendance, assignment management, performance analytics, role-based access, security, and instant notifications.',
    icon: LayoutDashboard,
    placement: 'top',
  },
  {
    target: '#faculty',
    title: 'Meet the Faculty',
    subtitle: 'CS Department leadership',
    content: 'Our CS Department is led by experienced educators and researchers driving innovation in CS education.',
    icon: Users,
    placement: 'bottom',
  },
  {
    target: '#how-it-works',
    title: 'How It Works',
    subtitle: '3 simple steps',
    content: 'Create your account, access your courses, and start tracking your progress — all in under 2 minutes.',
    icon: Zap,
    placement: 'bottom',
  },
  {
    target: '#faq',
    title: 'Got Questions?',
    subtitle: 'Frequently Asked Questions',
    content: 'Find answers to common questions about registration, attendance, assignments, and more.',
    icon: MessageCircle,
    placement: 'bottom',
  },
]

/* ──────── Student Dashboard Tour ──────── */
export const studentTourSteps = [
  {
    target: 'nav',
    title: 'Navigation Bar',
    subtitle: 'Move between pages',
    content: 'Use the top navigation to switch between Dashboard, Assignments, Attendance, Notices, and Materials.',
    icon: LayoutDashboard,
    placement: 'bottom',
  },
  {
    target: 'main',
    title: 'Student Dashboard',
    subtitle: 'Your overview',
    content: 'This is your home page. It shows enrolled courses, upcoming deadlines, and quick actions.',
    icon: BookOpen,
    placement: 'bottom',
  },
  {
    target: 'a[href="/student/assignments"]',
    title: 'My Assignments',
    subtitle: 'Submit your work',
    content: 'View all assignments, check deadlines, and upload your submissions directly from here.',
    icon: ClipboardList,
    placement: 'right',
  },
  {
    target: 'a[href="/student/attendance"]',
    title: 'My Attendance',
    subtitle: 'Track your presence',
    content: 'Monitor your attendance percentage across all enrolled courses with visual charts.',
    icon: CalendarCheck,
    placement: 'right',
  },
  {
    target: 'a[href="/student/notices"]',
    title: 'Notices',
    subtitle: 'Stay updated',
    content: 'Read announcements from admin and teachers. New notices show a badge count.',
    icon: Bell,
    placement: 'right',
  },
  {
    target: 'a[href="/student/materials"]',
    title: 'Study Materials',
    subtitle: 'Download resources',
    content: 'Access notes, slides, and reference materials uploaded by your teachers.',
    icon: FolderOpen,
    placement: 'right',
  },
]

/* ──────── Teacher Dashboard Tour ──────── */
export const teacherTourSteps = [
  {
    target: 'nav',
    title: 'Navigation Bar',
    subtitle: 'Teacher controls',
    content: 'Access all teacher tools from the top navigation — assignments, submissions, attendance, notices, and materials.',
    icon: LayoutDashboard,
    placement: 'bottom',
  },
  {
    target: 'main',
    title: 'Teacher Dashboard',
    subtitle: 'Your overview',
    content: 'See your assigned courses, pending submissions, and quick actions at a glance.',
    icon: BookOpen,
    placement: 'bottom',
  },
  {
    target: 'a[href="/teacher/create-assignment"]',
    title: 'Create Assignment',
    subtitle: 'Post new tasks',
    content: 'Create assignments with deadlines and max marks for your courses.',
    icon: ClipboardList,
    placement: 'right',
  },
  {
    target: 'a[href="/teacher/submissions"]',
    title: 'Submissions',
    subtitle: 'Review student work',
    content: 'View, grade, and provide feedback on student submissions.',
    icon: Users,
    placement: 'right',
  },
  {
    target: 'a[href="/teacher/attendance"]',
    title: 'Mark Attendance',
    subtitle: 'Record presence',
    content: 'Mark attendance for each class session with one tap per student.',
    icon: CalendarCheck,
    placement: 'right',
  },
  {
    target: 'a[href="/teacher/materials"]',
    title: 'Manage Materials',
    subtitle: 'Share resources',
    content: 'Upload notes, slides, and reference files for your students.',
    icon: FolderOpen,
    placement: 'right',
  },
]

/* ──────── Admin Dashboard Tour ──────── */
export const adminTourSteps = [
  {
    target: 'nav',
    title: 'Navigation Bar',
    subtitle: 'Admin controls',
    content: 'Full system management access — users, teachers, courses, semesters, enrollments, and notices.',
    icon: LayoutDashboard,
    placement: 'bottom',
  },
  {
    target: 'main',
    title: 'Admin Dashboard',
    subtitle: 'System overview',
    content: 'View total users, students, teachers, active accounts, and pending verifications.',
    icon: Users,
    placement: 'bottom',
  },
  {
    target: 'a[href="/admin/users"]',
    title: 'Manage Users',
    subtitle: 'User administration',
    content: 'Add, edit, verify, and manage all user accounts in the system.',
    icon: Users,
    placement: 'right',
  },
  {
    target: 'a[href="/admin/courses"]',
    title: 'Manage Courses',
    subtitle: 'Course catalog',
    content: 'Create, edit, and assign courses to teachers across semesters.',
    icon: BookOpen,
    placement: 'right',
  },
  {
    target: 'a[href="/admin/enrollments"]',
    title: 'Enrollments',
    subtitle: 'Student enrollment',
    content: 'Enroll students into courses and manage semester-wise enrollments.',
    icon: UserPlus,
    placement: 'right',
  },
  {
    target: 'a[href="/admin/examinations"]',
    title: 'Result',
    subtitle: 'Result management',
    content: 'Manage mid-term, final year, and complete result sheets for all courses.',
    icon: Trophy,
    placement: 'right',
  },
  {
    target: 'a[href="/admin/notices"]',
    title: 'Notices',
    subtitle: 'Announcements',
    content: 'Post and manage announcements visible to all users.',
    icon: Bell,
    placement: 'right',
  },
]
